# User Configuration for ${keyboard.name}

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# WPM: graph instead of speedometer
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=n
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE_MAX=100

# Luna dog animation (walks/runs with WPM)
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=y

# Modifier icons in macOS style
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=y
